site_name: "Suplemento de Grego"

theme:
  name: material
  logo: null
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking       # mellora o scroll e navegación lateral
    - search.suggest
    - search.highlight
    - search.share              # activa o buscador flotante tipo command palette
  palette:
    - scheme: default
      primary: white
      accent: red
  font:
    text: "Work Sans"
    code: "Fira Code"
  icon:
    repo: null

extra_css:
  - css/minimal.css

nav:
  - Inicio: index.md
  - Fonética:
      - Introdución: fonetica/index.md
      - Alfabeto: fonetica/alfabeto.md
      - Acentuación: fonetica/acentuacion.md
  - Morfoloxía:
      - Nominal: morfoloxia/nominal.md
      - Verbal: morfoloxia/verbal.md
  - Sintaxe:
      - Oración completa: sintaxe/oracion-completa.md
  - Semántica: semantica/index.md
  - Etimoloxía: etimoloxia/index.md
  - Probas PAU: pau/index.md

